### ISSUE TITLE
ORIOL

### ISSUE THREAD

**Issue by oriolprogamer712** [Mrbt0907/Weather2-Remastered#10]
HELLO HOW MUCH IS IT LEFT FOR THE MOD TO BE READY.

**Comment by Dovahkiin-Warrior** [comment]
Dev said sometime early or mid next year. Perfection takes time so just hang on to your hat!

**Comment by Mrbt0907** [comment]
Check out this project tracker if you want to see my progress with the update. I took this week off.

https://github.com/Mrbt0907/Weather2-Remastered/projects/1
