### ISSUE TITLE
Rain and storms are not compatible with shaders

### ISSUE THREAD

**Issue by Dovahkiin-Warrior** [Mrbt0907/Weather2-Remastered#11]
I'm sure you're already aware of the issue but maybe you can fix this if at all possible? When storms or rain happen, shaders like to make the sky look overcast and foggy and use their custom rain particles in vanilla. With the weather rewrite, this doesn't happen. I assume it is because the mod is not written to change vanilla weather and instead locks the weather to vanilla clear type so localized weather can occur. Is there any way this can be bypassed so our cool rain shaders can do their job? (Seus for example)

A second mention: The cloud particles don't look correct with all but custom made shaders, maybe there's a chance we could replace said cloud particles with something ever so slightly more compatible and what might look ever so slightly better? Thanks.

**Comment by Mrbt0907** [comment]
I won't be able to fix older shaders like seus since particles in there appears to be broken regardless of what I do.

I'll have to look into that later.

As for the rain fog not working with shaders correctly, I will have to do some experimentation with the code. I have a theory on what might be causing this issue and hopefully I can locate it soon.

I'll let you know when this issue is fixed.

**Comment by Dovahkiin-Warrior** [comment]
Thank you very much. This seems like a huge rewrite and I'm definitely going to consider having a second computer dedicated to playing this mod in its 1.12.2 phase for sure based on all the work I see planned out. I'm already excited for the future 1.16.5 release and look forward to seeing it in its completed form. One suggestion I have: Maybe replace the default minecraft thunder sounds, FireResistance27 made a decent weather resource pack (not affiliated of course), or even just maybe browse some youtube videos for good sounds for it^^. Once again, thanks for reviving a popular mod the community loves. I'll be sure to check back soon!

**Comment by oriolprogamer712** [comment]
I am doing this mod, this is not the one from 1.12.2 from mcreator and other programs that I am looking for to make the mod.

**Comment by Dovahkiin-Warrior** [comment]
The problem is make sure you get permission from the respective devs. Wouldn't want to potentially deal with an angry dev. You could probably help with development and I too have quite some experience in making mods and custom sounds and textures etc but just don't got the time with streaming and running servers for people.

**Comment by Mrbt0907** [comment]
I don't plan on releasing a build on any website but here until I can successfully get an alpha working and hopefully enough attention to potentially have Coro play test the update and maybe give me full permission to publish this mod for everyone to play.

I have been asking permission for maybe about a year now but I didn't get a response from him yet.

For now, this will remain as a unofficial fan update. I really hope he will like this update when it's finished.

**Comment by Dovahkiin-Warrior** [comment]
Thought I'd check back in, do we have any confirmed ETA for a 1.12.2 release and 1.16.5? I see coro has returned to work on weather2 with perlin noise tests but I fear it may be a while until we see a 1.16.5 official from coro himself and weather really gave me something to do in minecraft but having it missing in 1.16 is a big downer.

**Comment by Mrbt0907** [comment]
The alpha test will be released sometime this month if I keep up my pace. I am getting the new configs to work and then it should be ready for you guys to test.

**Comment by Dovahkiin-Warrior** [comment]
Sweeeeet! I can't wait. Do you have a Discord server that I could join to more easily stay up to date? I play 1.16.5 with several friends and we're all definitely interested in contributing anything we possibly can to the rework.

**Comment by Mrbt0907** [comment]
The rain fog should now work as of the current update. Your issue is fixed. I even added in some compatibility modes for some shaders.
