### ISSUE TITLE
Render clouds further than the render distance

### ISSUE THREAD

**Issue by Gliese-832-c** [Mrbt0907/Weather2-Remastered#110]
It would be amazing if you could somehow make it so that clouds render further than the configured render distance. (It could be a separate setting in the Weather2 config.) This will make the skies look so much better and make the world look bigger than it actually is. Especially for people who are playing at a render distance of 8 chunks, or even 6 chunks, this would immensely improve the gameplay experience, as you could see storms brewing up from much further away.

The only problem I see with this is that it could be quite hard to implement. You'd probably need to do some mixin or ASM trickery.

**Comment by Mrbt0907** [comment]
Already done for the next update.

**Comment by Gliese-832-c** [comment]
Holy shit. You are amazing. Thank you.
