### ISSUE TITLE
1.12.2 - Crash with Advanced Pollution

### ISSUE THREAD

**Issue by AffectAge** [Mrbt0907/Weather2-Remastered#128]
**Describe the bug**
Crash with advanced pollution, corrupted mod support
[crash-2022-12-31_13.21.42-server.txt](https://github.com/Mrbt0907/Weather2-Remastered/files/10327334/crash-2022-12-31_13.21.42-server.txt)

**Comment by Mrbt0907** [comment]
I cannot fix this on my end. They have to update their mod to support remastered.
