### ISSUE TITLE
Problem with sand storms

### ISSUE THREAD

**Issue by ghost** [Mrbt0907/Weather2-Remastered#13]
**Version**
forge 1.12.2 - v2855
weather2 - 1.12.2 - v2.6.12

**Describe The Issue**
Sandstorms occur naturally in cold biomes in certain world types with a custom generator like Biome O 'Plenty. For example, the "Cold Desert" biome is one of them.

**To Reproduce**
Just go to a cold biome with Weather2 and Biome O' Plenty (especially the cold desert biome). This event will happen on its own.

**Comment by Mrbt0907** [comment]
I have a feeling that sandstorms check the name of biomes instead of temperatures. I'll take a look at this issue when I can.

**Comment by nathiou** [comment]
I think this bug can be confirmed. I use RTG (Realistic Terrain Generation) and Biome O' Plenty.

![2021-12-18_20 23 21](https://user-images.githubusercontent.com/95654415/146653409-b763e136-6c44-4692-b050-e5b09197eece.png)

**Comment by Mrbt0907** [comment]
I can also confirm that if a biome has the name desert in it, sandstorms will spawn there. I'll add in a check to hopefully fix this issue. I'll return if I have this resolved.

**Comment by Mrbt0907** [comment]
I finally got to this issue and I hopefully fixed this issue. Please reopen this issue if it still persists in the upcoming alpha test.
