### ISSUE TITLE
1.12.2 - Players squashed by falling blocks crashes

### ISSUE THREAD

**Issue by CosmicHikari** [Mrbt0907/Weather2-Remastered#138]
Players being killed by flying blocks appears to cause the game to crash while mob death messages is installed. 
## I have not tested this without Mob Death Messages  to confirm if it is strictly that mod. It does appear to be, however.

**To Reproduce**
1. Install mob death messages
2. Summon a tornado
3. Catch a flying block with your face
4. game ded

**Logs and/or Screenshots**
[crash-2023-05-23_07.17.43-server.txt](https://github.com/Mrbt0907/Weather2-Remastered/files/11543154/crash-2023-05-23_07.17.43-server.txt)

**Comment by CosmicHikari** [comment]
Do we maybe have to request MDM's mod author add support for moving block?

eg with arrow:
https://github.com/multiplemonomials/Mob-Death-Messages/commit/00f6bd02dd87b353510d9894a91f660f5eb11587

**Comment by Mrbt0907** [comment]
This is an issue that I cannot fix on my end. The mod creator with the death messages assumed that all source entities would be a living entity, but in this case it is not. They need to either blacklist said block entity, or add support for entities that are not living entities.
