### ISSUE TITLE
<1.12.2> - <invisible rain and 0% rain when there is a storm>

### ISSUE THREAD

**Issue by YoshihiroFR** [Mrbt0907/Weather2-Remastered#139]
When I am in the forest biome I have rain particles without rain but when I go to the taiga biome there are more rain particles, and also it marks 0% rain when there is thunderstorms.

**Comment by Mrbt0907** [comment]
This is a known issue, and it's because the scene enhancer is not finding rain values correctly. The rain splashes with no rain cannot be fixed rn as that is hardcoded in Minecraft, but rain not showing up in certain circumstances is a bug, and should be fixed soon.

**Comment by Mrbt0907** [comment]
Fixed in the next update
