### ISSUE TITLE
Do you have plans to add this ramaster for 1.16.5?

### ISSUE THREAD

**Issue by FL4SHG1** [Mrbt0907/Weather2-Remastered#142]
**Do you have plans to add this ramaster for 1.16.5?
**
<Version 1.16.5 is the most stable currently corosus abandoned the mod so
how about you save this classic mod.>

**Comment by CosmicHikari** [comment]
Gotta wait for coro's permission and for us to finish 1.12.2 :P

**Comment by Mrbt0907** [comment]
Thanks to Fartsalot, I have permission to port to 1.16.5. I will port to 1.16.5 when update 3.0 is complete and I backported to 1.7.10

**Comment by oriolprogamer712** [comment]
how to port a version of this mod weather2 give me hints

**Comment by Mrbt0907** [comment]
Ask for permission from luna and corosus before you begin to port weather2

**Comment by oriolprogamer712** [comment]
thank you so much

**Comment by oriolprogamer712** [comment]
one more question who is luna and what is it only be corosus not luna help plis.

**Comment by Mrbt0907** [comment]
You can contact either of them and they will let you know if you can port it.
