### ISSUE TITLE
volcanoes spawn naturally

### ISSUE THREAD

**Issue by FL4SHG1** [Mrbt0907/Weather2-Remastered#151]
**volcanoes spawn naturally**
my idea is that this update comes out next year for the reason: there is still a lot to update, what do you think about the idea.

**Comment by Mrbt0907** [comment]
I don't have any plans to work on volcanos just yet. I'll consider it another time.

**Comment by CosmicHikari** [comment]
Volcanoes were only meant to be added in Tropicraft and currently only exist in w2r as part of Coro's code that will never likely be used. If we decide to implement erupting volcanoes and anything volcano, it will be far into the future (years down the line).

Thanks for the suggestion though!

Edit: clarification
