### ISSUE TITLE
1.12.2 - 2.8.8-indev from discord: - grabbed blocks "YEET BUG"

### ISSUE THREAD

**Issue by TeiBri** [Mrbt0907/Weather2-Remastered#152]
**Describe the bug**
Hi, I would like to report a bug in version 2.8.8indev from discord.
When you run tornado, it starts taking different blocks, which is fine. But the blocks take off VERY aggressively into the air and STILL (Even when they are above the tornado in the sky, they still fly up. So the tornado can never drop those blocks on the ground around it.

It would also be good if it was possible to customize the speed of the grabbed blocks, and also at what height the tornado should drop them to the ground again.

Thank you. :D (BTW THIS MOD IS ABSOLUTELY AMAZING!!!!! IM SO GLAD THAT YOU ARE STILL WORKING ON IT, WHEN COROUS DONT <3)

**Logs and/or Screenshots**
You will just see.

**Comment by CosmicHikari** [comment]
This could be related to the designated "yeet bug" where people are yeeted thousands of blocks into the air.

**Comment by Mrbt0907** [comment]
This will hence forth be known as the yeet bug. I'll fix this as soon as i can

**Comment by CosmicHikari** [comment]
I believe the "Yeet Bug" has since been fixed, as I am no longer able to replicate this issue.
