### ISSUE TITLE
1.12.2 - Wind pushes players in spectator mode

### ISSUE THREAD

**Issue by Gliese-832-c** [Mrbt0907/Weather2-Remastered#153]
**Describe the bug**
The title is pretty self-explanatory, if you are in gamemode 3 and there is a strong wind, you get pushed around.

**To Reproduce**
Wait for a storm to occur naturally or spawn one, then enter spectator mode.

**Logs and/or Screenshots**
N/A

**Comment by CosmicHikari** [comment]
This issue has been fixed in the latest indev. Please see the discord server ^^

**Comment by CosmicHikari** [comment]
**Link**: https://discord.gg/trNQFjZ26w
