### ISSUE TITLE
1.12.2 shader bug

### ISSUE THREAD

**Issue by Pinecone6442** [Mrbt0907/Weather2-Remastered#156]
it is sun during rain?
![2023-09-19_16 35 20](https://github.com/Mrbt0907/Weather2-Remastered/assets/111191736/d3a26e46-8eca-4463-b505-cd94d2a83634)

let it rain
let it rain

*

**Comment by Mrbt0907** [comment]
What version of the mod are you using? The latest one?

**Comment by Pinecone6442** [comment]
Yes I cant figure out how to fix it

**Comment by CosmicHikari** [comment]
Have you tried setting shader compatibility to BSL/COMP or any of the other options?

**Comment by Pinecone6442** [comment]
No I use a shader thats not on the list, there is an option in the normal weather2 to let it rain correctly

**Comment by Pinecone6442** [comment]
In the original weather2 Storm_Rain_Overcast_Amount=1.0 is what I do to fix it

**Comment by Mrbt0907** [comment]
Oh, do you use Overcast Mode? If so, setting that variable will fix your issue.

**Comment by Pinecone6442** [comment]
oh okay

**Comment by Pinecone6442** [comment]
doesnt work lol

**Comment by Mrbt0907** [comment]
Okay, could you send me your weather2 remastered config folder? I'll see if it's a config issue

**Comment by Pinecone6442** [comment]
no it isnt a config issue

**Comment by CosmicHikari** [comment]
Can you tell us the exact version of weather2 remastered you are running?

Not just 'latest', please give the exact file name of the jar. 

Also please upload your weather2remastered config folder.

Thanks!

**Comment by Pinecone6442** [comment]
nothing

**Comment by Mrbt0907** [comment]
I cannot reproduce this issue. I'm sorry that you are having this inconsistency.
