### ISSUE TITLE
<Describe Suggestion> a config to change the color of clouds and storms

### ISSUE THREAD

**Issue by Wither5575** [Mrbt0907/Weather2-Remastered#157]
**Suggestion**
<Describe your suggestion or question>
i thought it would be cool if you could have different colored tornados and stuff

**Comment by CosmicHikari** [comment]
You can. Just need to write your own renderer.

Alternatively in the advanced config of the latest indev alpha release you can change the renderer from 0 to 1 to use the weather 1 look and color system.

**Comment by Wither5575** [comment]
okay thank you for letting me know i can do that but i don't have that version tho

**Comment by CosmicHikari** [comment]
That version is available from the discord server.

The next release on curseforge will have the functionality included, so for now I recommend just hang tight for a few more weeks ^^

**Comment by Mrbt0907** [comment]
I am going to add color configs later down the line to the base mod.

**Comment by Wither5575** [comment]
Great!
