### ISSUE TITLE
1.7.10 port?

### ISSUE THREAD

**Issue by kotmatross28729** [Mrbt0907/Weather2-Remastered#158]
![99999Снимок](https://github.com/Mrbt0907/Weather2-Remastered/assets/110309314/2006aa34-5e08-43ec-98b0-0b73983ba570)

Hello, I just wanted to ask, you once wrote that after updating 1.12 to 3.0, you were going to make a port for 1.7.10, is that true?
The other day I fixed some bugs with shaders, however there is an issue where storms disappear  when re-entering the world, and I thought that if you want to port it to 1.7.10 (I hope so) , you might be fixing some bugs, so is there any point in waiting or should I *try* to fix this myself?
It's just that if you want to port it, then there is no point (for me) in wasting time on something that can be fixed by those who can do it really well.

**Comment by Mrbt0907** [comment]
Im not expecting to port for about two years or more with my current pace.

If you do plan on porting weather2 or weather2 remastered to 1.7.10 yourself, you need permission from Luna and Corosus to do so.
