### ISSUE TITLE
Picking up all blocks (including stone and bricks)

### ISSUE THREAD

**Issue by SSP6904** [Mrbt0907/Weather2-Remastered#160]
**Question**
Picking up all blocks (including stone and bricks)

I was wondering if there is a setting for picking up hard blocks like stone and bricks, but I can't seam to get that to work.

Can someone help me out?

**Comment by CosmicHikari** [comment]
If you want all blocks to be grabbed, change grab_list_blacklist to true and remove everything in the grab_list_entries config.

**Comment by SSP6904** [comment]
I did those settings, but the stone related blocks are not picked up

**Comment by Mrbt0907** [comment]
You need to also add those ids to the wind resistance list if you have strength grabbing/replacing enabled
