### ISSUE TITLE
Question about the wind

### ISSUE THREAD

**Issue by ghost** [Mrbt0907/Weather2-Remastered#17]
This is not totally a suggestion, nor a bug, but I would like to ask you an information about the mod wind config file. Maybe it will give an idea to improve it on your side? Why not :)

So here it is, I find that the wind in weather2 is often active. I would like to know if there was a way to make it rise more rarely or in Minecraft days.

I looked in the mod config, but I have no indication on the duration. For example, "globalWindChangeAmountRate" and "windSpeedMax". Basically globalWindChangeAmountRate is 1.0 and windSpeedMax the same.

I ask you this because you are more experienced than me in the mod and maybe I will understand these values. Thank you!

**Comment by Mrbt0907** [comment]
Let me look this up in the wind code tomorrow and I will get back to this question.

**Comment by nathiou** [comment]
Thank you. I will wait for your return!

**Comment by Mrbt0907** [comment]
windSpeedMax controls how fast winds can possibly go. This also controls how fast storms will move. globalWindChangeAmountRate changes how fast the wind will change to the new value, so lowering globalWindChangeAmountRate will make the transition much slower.

If you were receiving really fast winds constantly, then it may be highWindTimerEnableAmountBase. Raising this number increases how long the mod takes to start a high wind event in ticks. Same goes for lowWindTimerEnableAmountBase.

I may see if I can add better configurations to the wind system for you.

**Comment by nathiou** [comment]
So to reduce the wind event, I should decrease globalWindChangeAmountRate and increase highWindTimerEnableAmountBase and lowWindTimerEnableAmountBase for a smooth transition?

GlobalWindChangeAmountRate is set to 0.5. Maybe I could change it to 0.2 and double the tick values of highWindTimerEnableAmountBase and lowWindTimerEnableAmountBase?

I don't want it to be very rare, just decrease the transition. In the current system, it seems that the wind is programmed to blow at specific times.

**Comment by Mrbt0907** [comment]
Oh, then just increase the timer base values and ignore the global wind change variable. This should make it take much longer for the wind to blow fast.

**Comment by nathiou** [comment]
I'll do that then. Concerning the wind direction, is it random or is there a parameter in the configuration that affects it?

**Comment by Mrbt0907** [comment]
There is no configuration to adjust wind direction changes atm. The wind appears to somewhat be random, gotta look more into the code.
