### ISSUE TITLE
idea about the extended rendering distance of the weather2-remastered mod

### ISSUE THREAD

**Issue by oriolprogamer712** [Mrbt0907/Weather2-Remastered#181]
to add to the extended rendering distance of the weather2-remastered mod two more rendering options

1. Extreme

2. Very Extreme

**Comment by CosmicHikari** [comment]
Ultra creates a lot of lag as it is, so this will not likely be implemented at this moment.

**Comment by CosmicHikari** [comment]
You can also set a custom render distance in the advanced GUI in blocks (ultra is 2048 if I remember correctly)
