### ISSUE TITLE
Adding mod to a server will not work at all. Version 1.12.2, Forge:14.23.5.2860

### ISSUE THREAD

**Issue by Drakkoo3344** [Mrbt0907/Weather2-Remastered#183]
Adding the mod to a server will not work it shows all the blocks in a GUI but i cant place anything down and none of the commands work.

However on a singleplayer world the mod works just fine.

Uploading Base Profile 2024.02.04 - 11.41.59.02.mp4…

**Comment by Mrbt0907** [comment]
What kind of server are you using?

**Comment by Drakkoo3344** [comment]
> Owner

Im using pebble host right now, but the server jar file runs off of the same forge version, i tried wiping every config but i dont know if i have the wrong version of forge installed

**Comment by Mrbt0907** [comment]
Weather2 on curseforge uses the latest forge version (2860).

This appears to be an issue with your server host as I cannot reproduce this issue.

**Comment by Mrbt0907** [comment]
Could you send me the log file if you can?

**Comment by CosmicHikari** [comment]
Could you please attach  your latest.log and debug.log files here? They are in your server's /logs folder

**Comment by Drakkoo3344** [comment]
my mistakes

**Comment by Drakkoo3344** [comment]
Server was running on a vinilla file for whatever reason, no wonder i was missing half of my folders

**Comment by Mrbt0907** [comment]
Gotcha, glad you could get it resolved. Thank you for the server boost, I am very grateful :D
