### ISSUE TITLE
<1.12.2> - <Perfomance issues>

### ISSUE THREAD

**Issue by nveXyounes** [Mrbt0907/Weather2-Remastered#184]
**Describe the bug**

I'm encountering a problem with this mod, as well as experiencing a similar issue in the Weather2 mod. Whenever I gaze at the night sky, there's a significant drop in FPS.

**Comment by Mrbt0907** [comment]
Are you playing with any mods along side weather2 remastered?

**Comment by CosmicHikari** [comment]
Astral sorcery is known to conflict with weather2 remastered, looking at the aurora borealis causes massive frame drops.

Can recreate.

**Comment by nveXyounes** [comment]
@Mrbt0907 no im using Weather2 but not the remastered one.

**Comment by nveXyounes** [comment]
> Are you playing with any mods along side weather2 remastered?

EyesInTheDarkness-0.1.0.jar
additional_lights-1.12.2-1.2.1.2-optional.jar
AdvancementPlaques-1.12.2-1.4.10.jar
aether-1.12.2-v1.5.3.2.jar
AmbientSounds_v3.1.7_mc1.12.2.jar
animania-1.12.2-base-2.0.3.28.jar
animania-1.12.2-extra-1.0.2.28.jar
animania-1.12.2-farm-1.0.2.28.jar
AquaAcrobatics-1.15.2.jar
Atum-1.12.2-2.0.20.jar
AutoRegLib-1.3-32.jar
BackTools-1.12.2-7.0.1.jar
bettercaves-1.12.2-2.0.4.jar
BetterFps-1.4.8.jar
BetterMineshaftsForge-1.12.2-2.2.1.jar
betternether-0.1.8.5.jar
Biome_Bundle_O_Plenty-1.12.2_v1.0.jar
BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar
camouflagedcreepers-1.7.1.jar
carryon-1.12.2-1.12.6.20.jar
ChunkAnimator-1.12.2-1.2.1.jar
Clumps-3.1.2.jar
collective-1.12.2-3.0.jar
CoralReef-2.5-1.12.2.jar
coroutil-1.12.1-1.2.37.jar
CraftStudio-1.0.0.93-mc1.12-alpha.jar
CreativeCore_v1.10.70_mc1.12.2.jar
CreepyPastaCraft_Reborn_V2c-1.12.2-hotfix1.jar
davincisvessels-1.12-6.340-full.jar
DivineRPG-1.7.1.jar
DynamicSurroundings-1.12.2-3.6.3.jar
DynamicTrees-1.12.2-0.9.29.jar
DynamicTreesAtum-1.12.2-1.0.4.jar
DynamicTreesBOP-1.12.2-1.5.2.jar
ElectroblobsWizardry-4.3.9.jar
EnchantmentDescriptions-1.12.2-1.1.15.jar
end_spectre-1.0.jar
EnhancedVisuals_v1.4.4_mc1.12.2.jar
EpicSiegeMod-13.168.jar
FamiliarFauna-1.12.2-1.0.11.jar
fancylamps-1.2.1.jar
farsight-1.6.jar
FastFurnace-1.12.2-1.3.1.jar
Fish's+Undead+Rising-1.3.2.jar
foamfix-0.10.15-1.12.2.jar
FpsReducer-mc1.12.2-1.20.jar
getittogetherdrops-1.12.2-v1.0.2.jar
gravestone-1.10.3.jar
HMM16.2.1MC1.12.2.jar
Horror_elements_mod_1.5.2_1.12.2.jar
Hwyla-1.8.26-B41_1.12.2.jar
iChunUtil-1.12.2-7.2.2.jar
jei_1.12.2-4.16.1.302.jar
llibrary-1.7.20-1.12.2.jar
mahoutsukai-1.12.2-v1.19.55 16.22.35.jar
mcw-bridges-1.0.6b-mc1.12.2.jar
mcw-fences-1.0.0-mc1.12.2.jar
MobDismemberment-1.12.2-7.0.0.jar
MoBends_1.12.2-1.2.1-19.12.21.jar
movingworld-1.12-6.353-full.jar
mowziesmobs-1.5.8.jar
MutantBeasts-1.12.2-1.0.2.jar
Neat+1.4-17.jar
Nutrition-1.12.2-4.9.0.jar
OpenTerrainGenerator-1.12.2-v9.5-R1.jar
OptiFine_1.12.2_HD_U_G5.jar
OreLib-1.12.2-3.6.0.1.jar
Passive+Aggression-1.12.2-0.0.1.jar
Quark-r1.6-179.jar
randompatches-1.12.2-1.22.1.10.jar
RealisticTorches-1.12.2-2.1.2.jar
RenderLib-1.12.2-1.3.3.jar
savemystronghold-1.12.2-1.0.0.jar
SereneSeasons-1.12.2-1.2.18-universal.jar
SereneTweaks-1.0.jar
SnowRealMagic-1.12.2-0.7.1.jar
SpartanShields-1.12.2-1.5.5.jar
SRParasites-1.12.2v1.9.12.jar
starterkit_1.12.2-2.4.jar
stygian-1.0.4.jar
TenshiLib-1.12.2-1.2.4.jar
TheBetweenlands-3.9.6-universal.jar
tlskincape_1.12.2-1.4.jar
ToughAsNails-1.12.2-3.1.0.141-universal.jar
TravelersBackpack-1.12.2-1.0.35.jar
VanillaFix-1.0.10-150.jar
Waystones_1.12.2-4.1.0.jar
Weather2Remastered-1.12.2-2.8.11.jar
Xaeros_Minimap_23.9.7_Forge_1.12.jar
XaerosWorldMap_1.37.8_Forge_1.12.jar
zombieawareness-1.12.1-1.11.16.jar
Weather2Remastered-1.12.2-2.8.11.jar.dis

**Comment by nveXyounes** [comment]
> Are you playing with any mods along side weather2 remastered?

additional_lights-1.12.2-1.2.1.2-optional.jar
AdvancementPlaques-1.12.2-1.4.10.jar
aether-1.12.2-v1.5.3.2.jar
AmbientSounds_v3.1.7_mc1.12.2.jar
animania-1.12.2-base-2.0.3.28.jar
animania-1.12.2-extra-1.0.2.28.jar
animania-1.12.2-farm-1.0.2.28.jar
AquaAcrobatics-1.15.2.jar
Atum-1.12.2-2.0.20.jar
AutoRegLib-1.3-32.jar
BackTools-1.12.2-7.0.1.jar
bettercaves-1.12.2-2.0.4.jar
BetterFps-1.4.8.jar
BetterMineshaftsForge-1.12.2-2.2.1.jar
betternether-0.1.8.5.jar
Biome_Bundle_O_Plenty-1.12.2_v1.0.jar
BiomesOPlenty-1.12.2-7.0.1.2445-universal.jar
camouflagedcreepers-1.7.1.jar
carryon-1.12.2-1.12.6.20.jar
ChunkAnimator-1.12.2-1.2.1.jar
Clumps-3.1.2.jar
collective-1.12.2-3.0.jar
CoralReef-2.5-1.12.2.jar
coroutil-1.12.1-1.2.37.jar
CraftStudio-1.0.0.93-mc1.12-alpha.jar
CreativeCore_v1.10.70_mc1.12.2.jar
CreepyPastaCraft_Reborn_V2c-1.12.2-hotfix1.jar
davincisvessels-1.12-6.340-full.jar
DivineRPG-1.7.1.jar
DynamicSurroundings-1.12.2-3.6.3.jar
DynamicTrees-1.12.2-0.9.29.jar
DynamicTreesAtum-1.12.2-1.0.4.jar
DynamicTreesBOP-1.12.2-1.5.2.jar
ElectroblobsWizardry-4.3.9.jar
EnchantmentDescriptions-1.12.2-1.1.15.jar
end_spectre-1.0.jar
EnhancedVisuals_v1.4.4_mc1.12.2.jar
EpicSiegeMod-13.168.jar
EyesInTheDarkness-0.1.0.jar
FamiliarFauna-1.12.2-1.0.11.jar
fancylamps-1.2.1.jar
farsight-1.6.jar
FastFurnace-1.12.2-1.3.1.jar
Fish's+Undead+Rising-1.3.2.jar
foamfix-0.10.15-1.12.2.jar
FpsReducer-mc1.12.2-1.20.jar
getittogetherdrops-1.12.2-v1.0.2.jar
gravestone-1.10.3.jar
HMM16.2.1MC1.12.2.jar
Horror_elements_mod_1.5.2_1.12.2.jar
Hwyla-1.8.26-B41_1.12.2.jar
iChunUtil-1.12.2-7.2.2.jar
jei_1.12.2-4.16.1.302.jar
llibrary-1.7.20-1.12.2.jar
mahoutsukai-1.12.2-v1.19.55 16.22.35.jar
mcw-bridges-1.0.6b-mc1.12.2.jar
mcw-fences-1.0.0-mc1.12.2.jar
MobDismemberment-1.12.2-7.0.0.jar
MoBends_1.12.2-1.2.1-19.12.21.jar
movingworld-1.12-6.353-full.jar
mowziesmobs-1.5.8.jar
MutantBeasts-1.12.2-1.0.2.jar
Neat+1.4-17.jar
Nutrition-1.12.2-4.9.0.jar
OpenTerrainGenerator-1.12.2-v9.5-R1.jar
OptiFine_1.12.2_HD_U_G5.jar
OreLib-1.12.2-3.6.0.1.jar
Passive+Aggression-1.12.2-0.0.1.jar
Quark-r1.6-179.jar
randompatches-1.12.2-1.22.1.10.jar
RealisticTorches-1.12.2-2.1.2.jar
RenderLib-1.12.2-1.3.3.jar
savemystronghold-1.12.2-1.0.0.jar
SereneSeasons-1.12.2-1.2.18-universal.jar
SereneTweaks-1.0.jar
SnowRealMagic-1.12.2-0.7.1.jar
SpartanShields-1.12.2-1.5.5.jar
SRParasites-1.12.2v1.9.12.jar
starterkit_1.12.2-2.4.jar
stygian-1.0.4.jar
TenshiLib-1.12.2-1.2.4.jar
TheBetweenlands-3.9.6-universal.jar
tlskincape_1.12.2-1.4.jar
ToughAsNails-1.12.2-3.1.0.141-universal.jar
TravelersBackpack-1.12.2-1.0.35.jar
VanillaFix-1.0.10-150.jar
Waystones_1.12.2-4.1.0.jar
Xaeros_Minimap_23.9.7_Forge_1.12.jar
XaerosWorldMap_1.37.8_Forge_1.12.jar
zombieawareness-1.12.1-1.11.16.jar
Weather2Remastered-1.12.2-2.8.11.jar

**Comment by Mrbt0907** [comment]
Try playing with weather2 remastered alone and see  if it's related to weather2 at all.

**Comment by nveXyounes** [comment]
> Try playing with weather2 remastered alone and see if it's related to weather2 at all.

Description:
I've identified a potential conflict between the Weather2 (or Weather2 Remastered) mod and other mods in Minecraft. When running Minecraft with only the Weather2 mod, the problem is resolved. However, upon adding additional mods, the issue reoccurs.

Observations:
Upon closer inspection, I noticed a peculiar occurrence in the night sky. An unusual display of green and red light appears, leading to a significant FPS drop.

Resolution Attempt:
To mitigate the problem, I experimented with the configuration settings and found that enabling "potato pc mode" in the Weather2 mod config files successfully eliminated the issue.



<img width="583" alt="Screenshot 2024-02-12 at 19 07 16" src="https://github.com/Mrbt0907/Weather2-Remastered/assets/102386293/511ec764-82d4-4157-bfd7-c960510272ee">

**Comment by Mrbt0907** [comment]
This issue has only been seen once another time, and I could not find out which mod did the rendering glitch in the sky. Unfortunately unless you can find the mod that causes this conflict, I cannot resolve this issue easily.

I do not have time on my end to playtest for a good while, so if you or Fartsy can figure out which of the mods there causes it, that would be great for us moving forward.

**Comment by CosmicHikari** [comment]
Mod incompatibility identified. Dynamic Surroundings creates the aurora borealis, not astral sorcery.

Please edit your dynamic surroundings config and (if possible) disable the feature to confirm the incompatibility.

**Comment by nveXyounes** [comment]
> Mod incompatibility identified. Dynamic Surroundings creates the aurora borealis, not astral sorcery.
> 
> Please edit your dynamic surroundings config and (if possible) disable the feature to confirm the incompatibility.

Thank you for your assistance! Disabling the aurora borealis feature in Dynamic Surroundings indeed fixed the problem. I appreciate your suggestion and help. If I encounter any more issues or have questions, I'll be sure to reach out. Happy modding!

**Comment by nveXyounes** [comment]
> This issue has only been seen once another time, and I could not find out which mod did the rendering glitch in the sky. Unfortunately unless you can find the mod that causes this conflict, I cannot resolve this issue easily.
> 
> I do not have time on my end to playtest for a good while, so if you or Fartsy can figure out which of the mods there causes it, that would be great for us moving forward.

@Mrbt0907 
Thank you for your prompt response and for looking into the issue. I understand the challenges in identifying the specific mod causing the conflict, especially if it's a rare occurrence.

@ProfessorFartsalot played a crucial role in resolving the problem. It was determined that the issue originated from the dynamic surrounding's aurora.

**Comment by Mrbt0907** [comment]
Okay, then we have found the source of the incompatability.

I would like to figure out why weather2 hates Dynamic Surroundings arouras, but I am not skillful enough to fix it on my end at this time. So, I will for now ask people to turn off their arouras for Dynamic Surroundings for future issues related to this. I will mark this as closed for now unless the dev team returns to 1.12.2 to fix it on their end, or I figure out how to fix it and I will reopen this issue.

Thank you for the bug report, you have solved the source of a rare bug for me. I appreciate your patience and I hope you enjoy the mod!
