### ISSUE TITLE
1.12.2 - Rain and weather sounds don't work.

### ISSUE THREAD

**Issue by vainlaind4in** [Mrbt0907/Weather2-Remastered#190]
Simply put, there is no rain and there are no sounds coming from the tornadoes or even the rain at all. I'm not totally sure if this is the case, but it could be CubicChunks or Terrarium that might be messing with it.

1. Have the mods I have and load into a world
2. Spawn rain or tornado
3. No sound or rain (there are still lightning sounds)

Here's a screenshot:
![image](https://github.com/Mrbt0907/Weather2-Remastered/assets/113316836/4d83375b-0ce2-4310-98e2-2f2684fb40d1)
As you can see, there's no rain occuring at all. Rain doesn't even appear in rainstorms. I have all the effects set to max, and I tried playing around with enabling vanilla rain and the rain overrides and such, but to no avail.

Here's the log:
https://gist.github.com/vainlaind4in/7770723073c0d558c15591a1d3175cca
It's a mess, but to give you a little info so you don't need to dig too much; the "scene enhancer" feature becomes disabled when I load into any world. I'm not totally sure what this is, but it might connect to the missing of sounds and rain.

**Comment by Mrbt0907** [comment]
It looks like the crash detection system is working as intended. There appears to be a compatibility issue with one of those mods. My mod tries to look for a block, but for some reason the method used to get the block for each particle returns empty. With vanilla minecraft, it would at least return air.

I'll try to fix this with a temporary fix by assuming empty blocks are air blocks next patch. I would uninstall one of those to see which one causes the conflict.

**Comment by vainlaind4in** [comment]
Just tested it, CubicChunks is the culprit. Removed it and made a new world without it, and the rain and sounds work.

**Comment by vainlaind4in** [comment]
I am still looking forward to a fix of this bug.

**Comment by Mrbt0907** [comment]
The fix is coming in the next 2.9 update.

**Comment by vainlaind4in** [comment]
I will be using the previous alpha version of the mod in the mean time, as rain and sounds work fine on there.

**Comment by Mrbt0907** [comment]
That's your best bet as I didn't change the scene enhancer that update.
