### ISSUE TITLE
1.12.2 - Incompatible with Dynamic Trees?

### ISSUE THREAD

**Issue by rankieth** [Mrbt0907/Weather2-Remastered#193]
Tornadoes do not cause damage to trees when using the Dynamic Trees mod.

1. Install and load a world with dynamic trees installed
2. Summon  a tornado
3. See error

**Comment by Mrbt0907** [comment]
This is confirmed. You will have to manually add in the dynamic blocks to the grab list.

Dynamic Tree compatability is coming for 2.9, so be on the lookout for the next major update.

**Comment by Orvngex** [comment]
How do I manually add the dynamic leaves? It just says they're regular minecraft leaves when in game.

**Comment by rankieth** [comment]
If you press the f3 key it should tell you what they’re called

**Comment by CosmicHikari** [comment]
dynamictrees:leaves, dynamictrees:leaves0, dynamictrees:leaves1, dynamictrees:leaves2

You'll find all variations in the F3 menu. Add them to your wind resistance list if you use strength grabbing.

As a warning: Currently they leave 2px by 2px non connected branches that act like ghost blocks and trap players in them. Would highly advise not doing this. Instead, put the dynamictrees stuff in your replace list and replace them with air. Less realistic, yes. But better than having barely visible ghost blocks stopping your players from moving,

**Comment by CosmicHikari** [comment]
Official dynamic trees support comes later this year.
