### ISSUE TITLE
Deforestation and forests regrowing.

### ISSUE THREAD

**Issue by Jvk1166z** [Mrbt0907/Weather2-Remastered#197]
Hey, I'm posting this here because for some reason my curseforge account wont let me post it there.

I've got this mod installed on a 1.18.2 private server with my friends, and we all like it a lot, it looks amazing with our realistic terrain generation mods. I think the tornado tracks are really cool and add a lot of realism to the storms, so we don't want to disable block grabbing, but we've been noticing that there's starting to be a lot of deforestation in our world, due to repeated tornadoes, and I am unaware of a way to make those forests regrow over time without manually planting saplings.

Ideally I'd like to be able to keep the tornado tracks, but avoid the whole world eventually turning into a demolished wasteland. Is there any function in this mod, or any recommended mods to handle that? I've tried one that's supposed to make saplings plant themselves when they despawn instead of disappearing, but it doesn't seem to work on unloaded chunks, at least not that I've been able to verify myself, despite the tornadoes seeming to be able to damage those unloaded chunks.

Edit: I did just find out that supposedly it's vanilla behavior for the saplings to plant themselves, but again I haven't really noticed it myself and we have a hell of a lot of wrecked land on our map at this point that does not seem to be regrowing lol. Maybe I just haven't given it enough time?

**Comment by CosmicHikari** [comment]
Weather2-Remastered is only for 1.12.2 at the moment.

You must be using weather2 1.18.2, and thus we only can offer limited support at best. To my knowledge they do not have any option aside of maybe repair block mode if Coro added it in the 1.18 branch.

The weather2 GitHub is https://GitHub.com/Corosauce/Weather2

**Comment by Jvk1166z** [comment]
Ooh, yeah just got your two projects confused, sorry. Thanks for trying to help though! I'll go check with them.
