### ISSUE TITLE
La lluvia se detiene muy rápido 

### ISSUE THREAD

**Issue by misterclima** [Mrbt0907/Weather2-Remastered#200]
**Question**
<DPorque cuando una tormenta alcanza su máxima categoría que después empieza a debilitarse la lluvia para muy rápido en el weather2 original hasta que el tornado o el huracán
 no se disipará la lluvia no paraba

**Comment by Mrbt0907** [comment]
Voy a solucionarlo cuando siga trabajando en Weather2 Remastered. La lluvia cambiará de manera más realista en la próxima actualización importante.
