### ISSUE TITLE
<Describe Question>

### ISSUE THREAD

**Issue by misterclima** [Mrbt0907/Weather2-Remastered#201]
Como hacer que aparezcan tornados y huracánes superior a la fuerza 5 sin tener que usar comandos

**Comment by ProfessorFartsalot** [comment]
Puedes agregar un tamaño específico en la configuración avanzada, ejemplo: 

F10= 0.5

Para un 50% de chance de un tornado F10, o C10=0.5 para 50% de chance para un huracán de categoría 10.

![image](https://github.com/Mrbt0907/Weather2-Remastered/assets/16886014/0dc27f4b-b019-4261-b6b9-9259703bbdb0)

**Comment by ProfessorFartsalot** [comment]
Cerrado por inactividad.

ENG: Closed due to inactivity.
