### ISSUE TITLE
[Suggestion] - 1.16+ Port EZ Config 

### ISSUE THREAD

**Issue by rankieth** [Mrbt0907/Weather2-Remastered#204]
For the 1.16 (and maybe 1.18) port, could you change the 'EZ config' button to be a small button in the pause menu rather than a large bulky button on top of the screen? I'm using the create mod (featured in the image) as an example of how it could look.
![ideamrkrabs](https://github.com/Mrbt0907/Weather2-Remastered/assets/127988969/e26e477b-847e-4a8f-9c82-a271077b3186)
![2024-06-23_18 20 55](https://github.com/Mrbt0907/Weather2-Remastered/assets/127988969/eeb2b702-595f-4439-a0d7-4afca930700e)

![thing](https://github.com/Mrbt0907/Weather2-Remastered/assets/127988969/076f6b94-c65a-42ad-8fc4-4aa79c7c6756)

**Comment by Mrbt0907** [comment]
Not a bad idea, I just gotta see the common mods I usually play with and move the button to where I think it should be best placed.

**Comment by CosmicHikari** [comment]
I just saw the file names. All I can say is..

MISTER KRABS I HAVE AN IDEAAAAAAAA
