### ISSUE TITLE
Storms/Tornadoes I spawn all die out very quickly, and no storms spawn naturally

### ISSUE THREAD

**Issue by BabyPunchingMarathon** [Mrbt0907/Weather2-Remastered#205]
I've set the frequency to very common, edited some stuff in configs, but still no storms spawn naturally, and when I spawn something in manually, it always despawns in a minute or so. New to the mod though, haven't found anything about this though.

**Comment by Mrbt0907** [comment]
Did you accidentally turn on Overcast Mode/Global Weather mode by chance? That's what causes that to happen.

**Comment by BabyPunchingMarathon** [comment]
Yeah, turns out I had it on, thank you so much and good luck with the mod!

**Comment by Macintosh-Fan** [comment]
Why then does global weather mode mess it up?

**Comment by Mrbt0907** [comment]
Because it makes it to where storms can only spawn when the world begins to rain. If they try to form without rain, the storm disspates.
