### ISSUE TITLE
1.12.2 Command line Issue

### ISSUE THREAD

**Issue by popbot202** [Mrbt0907/Weather2-Remastered#209]
I'm having an issue where I can't use the command /storm kill all in multiplayer worlds when I created the world with cheats on.
![Screenshot 2024-07-17 153525](https://github.com/user-attachments/assets/7386b83d-e848-4c23-9f3d-0db6100fd9d7)

**Comment by popbot202** [comment]
No longer happens and now I can use it.

**Comment by CosmicHikari** [comment]
What did you do to fix it?

**Comment by popbot202** [comment]
> What did you do to fix it?

Gonna be honest, it just started working again after reopening the world.
