### ISSUE TITLE
<Minecraft Version 1.20> - <no EZ UI button>

### ISSUE THREAD

**Issue by Tattoosoffrogs** [Mrbt0907/Weather2-Remastered#212]
**Describe the bug**
I'm the owner of the realm and for some reason I don't have the EZ button. Is there something I need to check? I look when I game and pause it.
**To Reproduce**

**Logs and/or Screenshots**
If you have any crash logs, logs or screenshots to provide, attach them below.

**Comment by CosmicHikari** [comment]
Make sure your gui scale option is set to normal (2). There exists an issue where the ezgui button may not appear on large scaling.

**Comment by Mrbt0907** [comment]
Also, you have the wrong github page. We don't support og Weather2 here. This is for the remastered version of Weather2, which is only for 1.12.2
