### ISSUE TITLE
hurricane improvements and storms and clouds and adding curtains of rain

### ISSUE THREAD

**Issue by oriolprogamer712** [Mrbt0907/Weather2-Remastered#28]
Can you improve the
storms and
hurricanes
and add rain curtains Tell Corosauce to add rain curtains and to improve the hurricanes a little more and the clouds a little more tell him something else tell him to also add maximum and minimum particles of the rain curtains plis?

and one more thing Corosauce is already making the 1.18 version of weather2 storms.

**Comment by Dovahkiin-Warrior** [comment]
Yup, mrbt is working on the hurricanes already^^ also, this is a complete rewrite of the mod so I'm assuming it'll be very different from coros version with a lot more features. :D

**Comment by oriolprogamer712** [comment]
thanks for telling me

**Comment by Dovahkiin-Warrior** [comment]
Yup. I'm excited for the alpha test when it's ready haha

**Comment by oriolprogamer712** [comment]
I also can't stop watching the project every day haha

**Comment by Dovahkiin-Warrior** [comment]
Honestly same lol. But gotta be patient! Perfection takes time.

**Comment by Mrbt0907** [comment]
Distant rain curtains will be added in either the bug fix update or the update after that.

**Comment by Mrbt0907** [comment]
I have somewhat improved hurricanes and distant rain curtains are in the next update.
