### ISSUE TITLE
<1.12.2> - <no rain in latest release with weather machine>

### ISSUE THREAD

**Issue by zad112** [Mrbt0907/Weather2-Remastered#32]
no rain with weather machine. placed down and no clouds or rain form.
**To Reproduce**
go into game with latest release. place down weather machine (already set to rain) and wait.

**Comment by Mrbt0907** [comment]
I was able to replicate the issue and I will fix the weather machine when I can. I completely forgot about the weather machine and the weather deflector.

**Comment by Mrbt0907** [comment]
This bug is now fixed. I had to add a type to the storm to allow it to be picked up by everything in the mod. I really need to remove that type variable I designed. You are good to go when the next update drops.
