### ISSUE TITLE
1.12.2 - Intense Lag When Reloading Settings

### ISSUE THREAD

**Issue by Mrbt0907** [Mrbt0907/Weather2-Remastered#38]
**Describe the bug**
When a big modpack is used, changing any setting in the EZ Gui, ConfigMisc and ConfigGrab will cause intense lag.

**Comment by ProfessorFartsalot** [comment]
This is likely due to the way forge registers items. Typing /give @p <anything> will cause instant lag in 1.16.5 due to the game loading every item ID in the game.

**Comment by Mrbt0907** [comment]
Every time you change a setting that uses some sort of block list, it refreshes that list for every setting in that category.
This gets very laggy when you have a modpack with hundreds of items in the game.

I need to fix it by either using a thread, or somehow figuring out what was changed in the settings when refresh is called. The ladder will be really hard because the method that is called does not have any variables indicating what was changed.

**Comment by Mrbt0907** [comment]
Fixed in the next update
