### ISSUE TITLE
idea iron golem rain heavy

### ISSUE THREAD

**Issue by oriolprogamer712** [Mrbt0907/Weather2-Remastered#43]
new idea that the iron golem in a storm is afraid of strong storms
and the tornadoes
and hurricanes
like the villagers but in a different way
the golem is hiding under a tree or wooden roof
stone roof
obsidian roof and more blocks
under heavy rain.

**Comment by Mrbt0907** [comment]
I don't think iron golems are smart enough to preserve their own life like that, so I may not add this in the future depending on what people want. I'll re-open this if more people vote for this.

**Comment by Dovahkiin-Warrior** [comment]
This does make me wonder: Is it possible to make villagers go indoors during a strong storm, or modify village spawns to have tornado shelters?
