### ISSUE TITLE
Storms doesn't spawn in the world

### ISSUE THREAD

**Issue by ThunderNowX** [Mrbt0907/Weather2-Remastered#47]
I have installed the mod for Minecraft 1.12.2 forge, in mods folder, i launched game but there isn't any storms, rainy, thunderstorms, snowy. Nothing, i don't know how to solve this problem, i made something wrong or just a bug?
It doesn't spawn nothing, regarding weather. Can you please help? I'm waiting for answers. Thanks

**Comment by Mrbt0907** [comment]
By default, storms take a Minecraft day or two to spawn. You might just be getting unlucky. If you want more storms, head to the weather2 ez config in the pause menu under storms and change frequency of storms to a higher value. Contact me again if you don't see any natural storms after for at least 5 Minecraft days.

**Comment by ThunderNowX** [comment]
Now everything it's okay, thanks anyway for your advice i really appreciate that.
