### ISSUE TITLE
Better Cloud Visuals?

### ISSUE THREAD

**Issue by odvigajlo** [Mrbt0907/Weather2-Remastered#48]
**Suggestion**
<Describe your suggestion or question>
It would be great if clouds were more thicker, like theyre really thin and not realistic.
Maybe also better particles and more cloud types, like mammatus clouds, or shelf clouds?

**Comment by Dovahkiin-Warrior** [comment]
This request is made quite a lot on this repo - and it is something @Mrbt0907 is looking into but needs to see how the particles are spawned before it can be considered. But absolutely would like to see this happen.

**Comment by Mrbt0907** [comment]
Cloud improvements are planned for the next update. The main improvements I will be doing is distant downfall, storm visual improvements, and screen effects.

Feel free to comment on #8 for more cloud improvement suggestions.
