### ISSUE TITLE
Radar Overhaul Ideas

### ISSUE THREAD

**Issue by GGlitchX** [Mrbt0907/Weather2-Remastered#49]
**Suggestion**
<Describe your suggestion or question>
Hello Mrbt, I just found out about this mod today and I want to thank you SO MUCH for revamping this mod. I've been waiting for someone to actually finish and publish a revamp to this mod so I am very happy about this. I'm wishing you good success on this revamp and approval by Corosus :)

I know you are revamping the radar (pretty sure) so I thought I share some suggestions with you.

1. Possibly we could have different radar tiers?
The first radar could be a cheap radar with very little resources needed. All it could show is the current client and global weather and storms in a 1x1 radius with an unknown icon so it is unknown what type of storm it is.

The 2nd could be slightly better with a normal 3x3 but not many changes otherwise.

The 3rd could be a slightly better one showing radar icons for less significant storms like a t-storm or a supercell. Hail will not be shown. This could use the current crafting recipe we have right now.

The 4th tier could be a larger grid, showing all icons and some more radar information like the funnel windspeed. Will show tornado rating.

The 5th and final tier would be an even larger grid but like the standard radar, we have today. All features are shown.

I'd also like possibly a radar transmission block so you can link up an actual radar to the holographic screen. This way it would be more realistic, challenging and you get to see multiple locations for radars which could be useful if you want more accurate weather coming from a distance or if you are playing on a multiplayer server and want to see radar in other places to help out players on a different part of the world.

**Comment by Mrbt0907** [comment]
You got some things that I planned. I do plan on making tiered radars that display better information based on the tiers. The first tier will use the current recipe and only shows basic information about a storm and does not require any sensors. This will replace the current radar in the world.

The second tier radar has a slightly bigger detection range and shows what type of storm you are dealing with and where it is. However, you need to deploy sensors around the area to get any readings. You will need sensors for wind speed, humidity, etc. to get a good reading of a storm.

The final tier will have the biggest range, will display cloud formations, advanced storm information, and shows storm direction. This requires sensors to function.

I will be implementing wires to allow you to connect them together (Once I figure out how to do them). Power will not be required until I add in compatibility for various power types. Once that happens, there will be a config to disable power usage.

As for computer craft / open computer support, I am thinking about adding in compatibility for them at the end of the next update.

**Comment by GGlitchX** [comment]
> I second this. But instead of having 5 different radar recipes why not just craft a modular radar with those options as upgrades?
> 
> Edit: Wind speeds are usually measured by a Velocity radar. Therefore, we could have a velocity module be crafted that we upgrade the existing radar with in order to make it able to display wind speeds. (F0-F5, C0-C5 information).

Agree. Velocity radar would be nice but probably impossible for Mrbt to implement.

**Comment by GGlitchX** [comment]
> You got some things that I planned. I do plan on making tiered radars that display better information based on the tiers. The first tier will use the current recipe and only shows basic information about a storm and does not require any sensors. This will replace the current radar in the world.
> 
> The second tier radar has a slightly bigger detection range and shows what type of storm you are dealing with and where it is. However, you need to deploy sensors around the area to get any readings. You will need sensors for wind speed, humidity, etc. to get a good reading of a storm.
> 
> The final tier will have the biggest range, will display cloud formations, advanced storm information, and shows storm direction. This requires sensors to function.
> 
> I will be implementing wires to allow you to connect them together (Once I figure out how to do them). Power will not be required until I add in compatibility for various power types. Once that happens, there will be a config to disable power usage.
> 
> As for computer craft / open computer support, I am thinking about adding in compatibility for them at the end of the next update.

Great to hear!
