### ISSUE TITLE
Storm surge

### ISSUE THREAD

**Issue by Jaytv25** [Mrbt0907/Weather2-Remastered#57]
When a category 3 - ♾️ hurricane or a category 0 - ♾️ typhoon is in a area for a long time it will cause the world to flood up to 12 blocks from the source and the most aggressive part when it storm surges is the centre of one

Here is a image I hope shows up
![20220526_102244](https://user-images.githubusercontent.com/105985096/170830502-3dc25ac0-f4fb-4102-ad35-bc5b5e1acd63.jpg)

**Comment by Mrbt0907** [comment]
Water buildup is currently not planned to be implemented. I might consider this in a future update. I will close this for now.
