### ISSUE TITLE
/storm create sandstorm command doesn't work

### ISSUE THREAD

**Issue by g-gi-g** [Mrbt0907/Weather2-Remastered#58]
When I try to use the command the only response is "Failed to create a storm as one or more parameters are incorrect". I tried to create sandstorm in superflat dessert or in normal dessert but it didn't work.

**Comment by Mrbt0907** [comment]
I can confirm this bug exists and is my fault for not properly integrating sandstorms to the new command. I will fix this in the next update.

For now, you won't be able to manually create sandstorms.

**Comment by Mrbt0907** [comment]
This bug is fixed in the next patch.
