### ISSUE TITLE
Enforce requirements to avoid issues in game

### ISSUE THREAD

**Issue by Dovahkiin-Warrior** [Mrbt0907/Weather2-Remastered#60]
Most mods available for Minecraft do a thing where they refuse to load the game if A) Forge is outdated or B) A dependency is outdated.

I suggest that you enforce checking for Minecraft Forge version >= 14.23.5.2860 and coroutil >=  1.2.37 (or >= 1.2.36 if you like, 37 is the latest for 1.12.2 though). Doing so would prevent a lot of potential false bug reports^^

Edit: 1.2.37 of coroutil's changelog suggests a massive performance gain (on larger servers), so requiring it would be ideal.
> - Improve chunk data grid performance on large servers by supporting partial nbt write outs.

**Comment by Mrbt0907** [comment]
I will implement this in the next update. Hopefully this prevents further issues in the future.

**Comment by Mrbt0907** [comment]
This is added in the next patch.
