### ISSUE TITLE
Non Server Operators Shouldn't Be Able To Chance ADV. Config & normal config.

### ISSUE THREAD

**Issue by GGlitchX** [Mrbt0907/Weather2-Remastered#61]
This is a big problem for me and a lot of other tornado survival servers as people can mess around with the settings and cause chaos in Minecraft Servers. Possibly this could change? I assume it wouldn't be too hard but it would be SUPER good for me trying to start a server.

**Comment by Mrbt0907** [comment]
This isn't a suggestion, but a bug. I'll investigate this issue as soon as I can.

**Comment by Mrbt0907** [comment]
I can confirm that this is not a real issue. You are safe against greifers.
