### ISSUE TITLE
Windspeed category damage should be configureable.

### ISSUE THREAD

**Issue by GGlitchX** [Mrbt0907/Weather2-Remastered#62]
Instead of having all tornadoes picking up the same, they should pick up different blocks depending on their wind speed/EF category. The pick-up rate should also be customizable. Some default suggestions:

EF-0 Glass, wood planks, grass (plant), leaves. Super low pick-up rate.
EF-1 Glass, wood planks, grass (plants), leaves, logs. sand, clay, gravel, wool. Low pick-up rate.
EF-2 Glass, wood planks, grass (plants), leaves, logs, wood fences, wood stairs/roof, doors. Medium pick-up rate.
EF-3 Glass, wood planks, grass (plants), leaves, logs, all stairs, all fences, cobblestone, concrete, stone, stone bricks, bricks, doors Fast pick up rate.
EF-4. Glass, wood planks, grass (plants), leaves, logs, all stairs, all fences, cobblestone, concrete, stone, stone bricks, bricks, iron bars, iron doors, doors  Very fast pick up rate.
EF-5 EF-4, but extreme pick-up rate. Picks up fluid blocks.

**Comment by Mrbt0907** [comment]
This is already a feature in the current update. See the advanced settings under Grab. The config **wind_resistance_entries** allows you to change the wind resistance of the block in question by doing **minecraft:grass=100**. This makes it to where grass can only be picked up if the funnel speed reaches 100 mph.

As for pickup rates, I will consider this either at the end of the next update or on a future update.
