### ISSUE TITLE
Weather Radar shows rain but it is not raining

### ISSUE THREAD

**Issue by RadekWeather** [Mrbt0907/Weather2-Remastered#66]
https://scontent-frt3-2.xx.fbcdn.net/v/t39.30808-6/287182551_1678141659210679_5822880962464861420_n.jpg?_nc_cat=101&ccb=1-7&_nc_sid=730e14&_nc_ohc=w8lFtgDk4n4AX-OMrbA&_nc_oc=AQniVTNKhi-8dg3tFAgAqQBfqutKDqT0L1NiMI42bGxuwksGZNbGho5hjKjOjl5tg8k&_nc_ht=scontent-frt3-2.xx&oh=00_AT88eJ2vQvU51KkiSRul-J4crAsUobE_ih9Wc2sQ54xzFg&oe=62A81698

**Comment by Mrbt0907** [comment]
If you can, please send the file directly do I can figure out what you are encountering.

I also need an explanation on what happened.

**Comment by RadekWeather** [comment]
Configuration file?

**Comment by Mrbt0907** [comment]
Preferably a screenshot and context of the situation if possible.

**Comment by RadekWeather** [comment]
Basically I provided a link above for the screenshots.

**Comment by RadekWeather** [comment]
I use mods like:

Dynamic Surroundings, Serene Seasons, lightning tweaks.

**Comment by ProfessorFartsalot** [comment]
Can you give us your forge version and coroutil version? As well as weather2 remastered version?

**Comment by RadekWeather** [comment]
> Can you give us your forge version and coroutil version? As well as weather2 remastered version?

Forge 14.23.5.2860
CoroUtil 1.2.37
Weather2 Remastered alpha 2.7.7

**Comment by RadekWeather** [comment]
<img src="https://i.imgur.com/hX6f1hy.png

**Comment by RadekWeather** [comment]
![obraz](https://user-images.githubusercontent.com/96982537/173895285-14fcf657-d986-40a7-8c76-0f86bac430ad.png)

**Comment by ProfessorFartsalot** [comment]
Yeah this is related to #39 which will be fixed in the next release. I believe @Mrbt0907 said reconnecting would make a storm spawn when this happens.

**Comment by Mrbt0907** [comment]
This is not related to #39 actually. The rainstorm is there, but the particles are not showing up. Please go to your config folder and send me this file: **config/Weather2/Particle.cfg**.

I have a feeling on what it may be.

**Comment by RadekWeather** [comment]
[Particle.odt](https://github.com/Mrbt0907/Weather2-Remastered/files/8916068/Particle.odt)

**Comment by RadekWeather** [comment]
> This is not related to #39 actually. The rainstorm is there, but the particles are not showing up. Please go to your config folder and send me this file: **config/Weather2/Particle.cfg**.
> 
> I have a feeling on what it may be.
[Particle.odt](https://github.com/Mrbt0907/Weather2-Remastered/files/8916059/Particle.odt)

**Comment by Mrbt0907** [comment]
Please send the file in its original state. It should be a .cfg file.

**Comment by RadekWeather** [comment]
>

**Comment by RadekWeather** [comment]
A moment because I'm just starting to use github

**Comment by ProfessorFartsalot** [comment]
The optimal way to send CFG files would be to use GitHub's [GIST](https://gist.github.com). Open your CFG file in an editor, select all text, copy it, then paste it into the GIST upload box, name the file Particle.cfg and create a secret GIST. Then send the link in your post. However, assuming your config file is exactly as GitHub shows it (which seems to be the case according to Particle.odt which you sent already... You have vanilla rain/thunder enabled only. This is known as Overcast Mode. Line 63 (B:use_vanilla_rain_and_thunder=true) please change that to instead be false.

`B:use_vanilla_rain_and_thunder=false`

Launch your game and in your world, hit ESC, go to Weather2 EZ Config then under System, verify Enable Global Weather is Off. If it is, Save and Exit.

![image](https://user-images.githubusercontent.com/16886014/174117522-45195503-bc12-462e-b725-6c28c46679f9.png)



At present, global weather mode does not spawn rain even if a rain storm exists, as the server's weather state is supposed to govern whether it rains or not, this may be your issue.



As a side note @Mrbt0907, enabling/disabling global weather does not appear to set use vanilla rain/thunder true or false. It leaves it at whatever the config file presently has.

**Comment by RadekWeather** [comment]
> The way you sent it should be fine. You are doing great for just starting to use GitHub.



> Please send the file in its original state. It should be a .cfg file.


> The optimal way to send CFG files would be to use GitHub's [GIST](https://gist.github.com). Open your CFG file in an editor, select all text, copy it, then paste it into the GIST upload box, name the file Particle.cfg and create a secret GIST. Then send the link in your post. However, assuming your config file is exactly as GitHub shows it (which seems to be the case according to Particle.odt which you sent already... You have vanilla rain/thunder enabled only. This is known as Overcast Mode. Line 63 (B:use_vanilla_rain_and_thunder=true) please change that to instead be false.
> 
> `B:use_vanilla_rain_and_thunder=false`
> 
> Save Particle.cfg then launch your game and in your world, hit ESC, go to Weather2 EZ Config then under System, verify Enable Global Weather is Off. If it is, Save and Exit. If your EZGUI looks like mine, please use **/storm kill all** followed by **/storm create rain** to see if rain is working again.
> 
> ![image](https://user-images.githubusercontent.com/16886014/174117522-45195503-bc12-462e-b725-6c28c46679f9.png)
> 
> At present, global weather mode does not spawn rain even if a rain storm exists, as the server's weather state is supposed to govern whether it rains or not, this may be your issue.
> ## If the above does not fix it, please close the game and delete all files in config/weather2 and then reload the game.
> 
> As a side note @Mrbt0907, enabling/disabling global weather does not appear to set use vanilla rain/thunder true or false. It leaves it at whatever the config file presently has.
> 
> Edited: Added more specific details and a rain test request.

I did everything

> The optimal way to send CFG files would be to use GitHub's [GIST](https://gist.github.com). Open your CFG file in an editor, select all text, copy it, then paste it into the GIST upload box, name the file Particle.cfg and create a secret GIST. Then send the link in your post. However, assuming your config file is exactly as GitHub shows it (which seems to be the case according to Particle.odt which you sent already... You have vanilla rain/thunder enabled only. This is known as Overcast Mode. Line 63 (B:use_vanilla_rain_and_thunder=true) please change that to instead be false.
> 
> `B:use_vanilla_rain_and_thunder=false`
> 
> Save Particle.cfg then launch your game and in your world, hit ESC, go to Weather2 EZ Config then under System, verify Enable Global Weather is Off. If it is, Save and Exit. If your EZGUI looks like mine, please use **/storm kill all** followed by **/storm create rain** to see if rain is working again.
> 
> ![image](https://user-images.githubusercontent.com/16886014/174117522-45195503-bc12-462e-b725-6c28c46679f9.png)
> 
> At present, global weather mode does not spawn rain even if a rain storm exists, as the server's weather state is supposed to govern whether it rains or not, this may be your issue.
> ## If the above does not fix it, please close the game and delete all files in config/weather2 and then reload the game.
> 
> As a side note @Mrbt0907, enabling/disabling global weather does not appear to set use vanilla rain/thunder true or false. It leaves it at whatever the config file presently has.
> 
> Edited: Added more specific details and a rain test request.

I did everything, I have overcast mode turned off and nothing has changed
https://i.imgur.com/dAfGgdL.png

**Comment by ProfessorFartsalot** [comment]
Alright, turn overcast mode on, do **/storm kill all**, then turn it off again and do **/storm kill all** again, then **/storm create rain**. 

I will test this with only weather2 and coroutil meanwhile.

**Comment by ProfessorFartsalot** [comment]
Can you see the sun when you do **/storm create thunder ~ ~** ? And does chat say you spawned a new thunderstorm? Can you send a screenshot of this EZGUI screen? 
![image](https://user-images.githubusercontent.com/16886014/174136333-f321e95b-0f40-412a-8169-9831cfa655b3.png)

**Comment by RadekWeather** [comment]
> 

I did it and nothing has changed. after typing /storm create rain I get thunderstorms not rainy weather, it rains a little during a thunderstorm, in rainy weather it does not rain at all.

**Comment by RadekWeather** [comment]
> 

![obraz](https://user-images.githubusercontent.com/96982537/174138052-0c0ff7d2-4350-4e49-a166-b7ff14f946d4.png)
![obraz](https://user-images.githubusercontent.com/96982537/174138119-0cde100e-de15-4d69-b0b0-5f5ed9087862.png)
During a storm, the sky gets dark, chat popping out about the storm, and there is such a problem after pressing F1

**Comment by ProfessorFartsalot** [comment]
Can you try changing the various quality options in the EZGUI to match mine momentarily? I haven't seen this issue before, so may need to wait for @Mrbt0907 to log on and have a look at this.

**Comment by RadekWeather** [comment]
> Can you try changing the various quality options in the EZGUI to match mine momentarily? I haven't seen this issue before, so may need to wait for @Mrbt0907 to log on and have a look at this.

Ok i will do that :)

**Comment by RadekWeather** [comment]
> Can you try changing the various quality options in the EZGUI to match mine momentarily? I haven't seen this issue before, so may need to wait for @Mrbt0907 to log on and have a look at this.

I uninstalled weather2 and I did the test will there still be this problem after pressing F1 and unfortunately something broke for me
![obraz](https://user-images.githubusercontent.com/96982537/174142432-59d688b5-cefa-4d3b-a27b-4fde7fd5a3ad.png)

**Comment by Mrbt0907** [comment]
I belive I found your issue.

```
# Should rain show up?
B:enable_rain=true
```

and

```
# Enables vanilla rain and thunder only
B:use_vanilla_rain_and_thunder=true
```

should be off. Turn those settings off and the rain should turn back on.

**Comment by Mrbt0907** [comment]
As for the rendering issues, I have no idea what could be causing that because I only had that happen to me twice. I'll try to look more into it when I can.

**Comment by RadekWeather** [comment]
> As for the rendering issues, I have no idea what could be causing that because I only had that happen to me twice. I'll try to look more into it when I can.

I think it works already, I will check tomorrow and write back.

**Comment by RadekWeather** [comment]
> As for the rendering issues, I have no idea what could be causing that because I only had that happen to me twice. I'll try to look more into it when I can.

I checked and it's not raining as i have rainy weather.

**Comment by Mrbt0907** [comment]
Wait, I do see the rain in one of the screenshots. It appears you are having a big rendering issue because the rain particles won't render in your sky. It renders in front of a tree based on the screenshot.

I have a feeling it's an incompatibility with your computer, and I can't really address that right now since I am not skilled enough to find a solution to system incompatibilities right now.  Your last option is to play around with the Shader Compatability option in  EZ Gui -> Quality.

If none of those work, then I will just have to learn how to modify how particles render with the mod. I apologize for the slow support.

**Comment by RadekWeather** [comment]
> Wait, I do see the rain in one of the screenshots. It appears you are having a big rendering issue because the rain particles won't render in your sky. It renders in front of a tree based on the screenshot.
> 
> I have a feeling it's an incompatibility with your computer, and I can't really address that right now since I am not skilled enough to find a solution to system incompatibilities right now. Your last option is to play around with the Shader Compatability option in EZ Gui -> Quality.
> 
> If none of those work, then I will just have to learn how to modify how particles render with the mod. I apologize for the slow support.

Thank you for the answer :)

**Comment by RadekWeather** [comment]
> Could you press f3 and give us a screenshot of your game with that information on screen?

![obraz](https://user-images.githubusercontent.com/96982537/174351833-dc1397d0-4619-4ed8-a8f7-257a2b68e794.png)

**Comment by ProfessorFartsalot** [comment]
Seems your graphics card is ATI (AMD). As far as I'm aware, some shaders are troublesome with AMD so like as @Mrbt0907 said, some shader settings need be tweaked to make the particles more compatible. I'm not sure if he's mentioned the `particleShaders` yet in the advanced config, but if you have a moment: Keep note of that setting's default value (I believe false?) then try setting it to true and see if that makes a difference. If it's already true, try false. Although obvious, check your video settings -> animations and make sure all particles are on.

If none of that makes a difference try changing various advanced options related to particles and/or shaders and post here if you find anything of course ^^ . I do not presently own any systems with ATI graphics or I'd also do some testing. Thanks again.

**Comment by RadekWeather** [comment]
> Seems your graphics card is ATI (AMD). As far as I'm aware, some shaders are troublesome with AMD so like as @Mrbt0907 said, some shader settings need be tweaked to make the particles more compatible. I'm not sure if he's mentioned the `particleShaders` yet in the advanced config, but if you have a moment: Keep note of that setting's default value (I believe false?) then try setting it to true and see if that makes a difference. If it's already true, try false. Although obvious, check your video settings -> animations and make sure all particles are on.
> 
> If none of that makes a difference try changing various advanced options related to particles and/or shaders and post here if you find anything of course ^^ . I do not presently own any systems with ATI graphics or I'd also do some testing. Thanks again.

I have everything set to true in the animation.

**Comment by Mrbt0907** [comment]
I'll try to fix this in the next update if I can.
