### ISSUE TITLE
new settings menu going off bottom of screen

### ISSUE THREAD

**Issue by Justin7654** [Mrbt0907/Weather2-Remastered#69]
![image](https://user-images.githubusercontent.com/95324492/173604789-6530c924-bb72-4560-acf7-5d854531bc82.png)
Its also worse in window mode

**Comment by Justin7654** [comment]
also can you add a reset all to default option

**Comment by Justin7654** [comment]
also i have a high wind lightning storm on the water but it has a water spout in the water? The radar doesn't say its a tornado

**Comment by odvigajlo** [comment]
> also i have a high wind lightning storm on the water but it has a water spout in the water? The radar doesn't say its a tornado

About Waterspout even in orginal mod it has shown as regular thunderstorm, and looks like your window shifted because of your screen resolution

**Comment by Dovahkiin-Warrior** [comment]
> how do i fix the window?

Options -> GUI Settings -> GUI Scale Normal


> also can you add a reset all to default option

Good idea. I second this.

**Comment by Justin7654** [comment]
i don't see "GUI Settings", what options menu the minecraft one?

**Comment by Dovahkiin-Warrior** [comment]
Yes.

**Comment by Dovahkiin-Warrior** [comment]
It might just be called GUI scale. Just click it until the GUI is normal size.

**Comment by Justin7654** [comment]
ok its fixed, im not a fan of everything not the mod being super tiny but it will work, thanks
