### ISSUE TITLE
Add EZGUIConfig button to restore all settings to defaults

### ISSUE THREAD

**Issue by ProfessorFartsalot** [Mrbt0907/Weather2-Remastered#71]
# This idea came from @[Justin7654](https://github.com/Justin7654) in issue #69 .

_I thought I would open this suggestion to make it easier to manage in the Projects tab._

Add a config button that resets all values to what they are when the config files are originally created. Then if people have issues like #66  or if someone edits an advanced setting and breaks the game, they can restore the default config files and reload the config to fix their weather2 setup.

**Comment by Mrbt0907** [comment]
Will be added in the next update

**Comment by Mrbt0907** [comment]
Your welcome

**Comment by CosmicHikari** [comment]
**THANKS BOSS, FOR REAL FOR REAL. SAVED MANY MANY ISSUES LOL**
