### ISSUE TITLE
<Describe Question>

### ISSUE THREAD

**Issue by Zachhoff1** [Mrbt0907/Weather2-Remastered#74]
**Question**
Can someone make like a YouTube video or something of how to compile this mod? I'm having issues and don't know what versions of Java I need or the steps to take to make it compile

**Comment by Mrbt0907** [comment]
You will need to use Forge 1.12.2-14.23.5.2847. I use java 1.8 to compile the mod, and you will need coroutil 1.12.1-1.2.37. If you use eclipse, run `gradlew setupDecompWorkspace eclipse` in the workspace.

If it's successful, then you are ready to go.

I believe the source code right now is the same as the current build out right now. That will change soon however.

**Comment by Zachhoff1** [comment]
Thanks I'll give that a try

**Comment by Mrbt0907** [comment]
Almost forgot, you need to install Obfuscate 0.4.2-1.12.2 and Mrcrayfish's Vehicle Mod 0.44.1-1.12.2
