### ISSUE TITLE
1.12.2 Forge 14.23.52860 - Random Crash Soon After Getting In Game

### ISSUE THREAD

**Issue by Desoroxxx** [Mrbt0907/Weather2-Remastered#86]
**Describe the bug**
The game crash after a few minutes of playing a world

**To Reproduce**
1. Launch Minecraft
2. Create a world
3. After a few minutes crash

**Logs and/or Screenshots**
https://www.toptal.com/developers/hastebin/lanikujowi.rb

**Comment by Mrbt0907** [comment]
It appears that Weather2 Remastered is not compatable with Forge Endertech and Pollution Of The Realms. They need to update the classes on their end to support Weather2 Remastered.

I cannot fix this on my end. Sorry.

**Comment by JustDesoroxxx** [comment]
Thanks I reported it to them, will keep you updated

**Comment by JustDesoroxxx** [comment]
So I got an answer which is that Forge Endertech and Pollution Of The Realms will only be updated when W2 Remastered is released

**Comment by Mrbt0907** [comment]
Really smart idea on their end. For now until 2.8 releases, Pollution of the realms will be incompatible. Sorry man.

**Comment by Mrbt0907** [comment]
The update is now out, and it is possible for them to fix the compatibility now.
