### ISSUE TITLE
How can I ask corosus permission to test the mod?

### ISSUE THREAD

**Issue by oriolprogamer712** [Mrbt0907/Weather2-Remastered#87]
How can I ask corosus permission to test the mod?
I leave you this link https://www.youtube.com/watch?v=7ofFDxTefbU&t=55s
https://github.com/Corosauce/Weather

**Comment by Mrbt0907** [comment]
Leave him an email or ask him on his github.

I'm still trying to get into contact with him to this day.

**Comment by oriolprogamer712** [comment]
how do i do it
