### ISSUE TITLE
How can I get this permission

### ISSUE THREAD

**Issue by oriolprogamer712** [Mrbt0907/Weather2-Remastered#88]
how can i get this permission please help

**Comment by oriolprogamer712** [comment]
Pls

**Comment by oriolprogamer712** [comment]
Also, since I don't know how to solve the problems of the weather mod code, I'm in the eclipse program and I have a clever idea, but I can't figure out how to solve this. I'll send you a link with what's happening to me.

**Comment by ProfessorFartsalot** [comment]
There is no other way than to email him or post on his repo. This repository is only for weather2 remastered.

**Comment by oriolprogamer712** [comment]
![Screenshot_2022-08-06-16-19-26-557_com.whatsapp.jpg](https://user-images.githubusercontent.com/92949450/183252854-b7a44a3e-77c2-4a69-9e09-40d9d877831d.jpg)

**Comment by oriolprogamer712** [comment]
please help😭😞😞

**Comment by ProfessorFartsalot** [comment]
Please open an issue on the repository this is related to. Weather2 Remastered is a passion project and is not related to the original weather2.

**Comment by oriolprogamer712** [comment]
https://github.com/Corosauce/Weather

**Comment by Mrbt0907** [comment]
Create an issue on his repository or find his email if you can if you want to get permission to modify his code.
