### ISSUE TITLE
Como resuelvo los problemas de eclipse ide.

### ISSUE THREAD

**Issue by oriolprogamer712** [Mrbt0907/Weather2-Remastered#89]
How do I solve the problems of eclipse ide of the project this Weather 2-Remastered

**Comment by Mrbt0907** [comment]
Download MrCrayfish's Vehicle Mod
Download Obfuscate
Download Coroutil
Place these mods in the lib folder (Create the folder in your project folder if it doesn't exist)
run "gradlew setupDecompWorkspace eclipse"

**Comment by oriolprogamer712** [comment]
![IMG_20220809_113952.jpg](https://user-images.githubusercontent.com/92949450/183617374-963f3c47-6b99-4f53-bfbb-c86d7387c497.jpg)
