### ISSUE TITLE
leaves foliage add

### ISSUE THREAD

**Issue by oriolprogamer712** [Mrbt0907/Weather2-Remastered#95]
Do I have an idea? Is it possible to add foliage to the trees that move the square leaves?

I leave you a link of an image I made.

**Comment by oriolprogamer712** [comment]
![png-transparent-minecraft-story-mode-tree-oak-birch-oak-glass-grass-cross-thumbnail.png](https://user-images.githubusercontent.com/92949450/187083112-18186165-b637-4a01-bec9-95f21dbecfb1.png)

**Comment by Mrbt0907** [comment]
For the time being, this is impossible with my current skillset. I cannot add this to the mod.
