### ISSUE TITLE
Biome Storm Test able to report an impossible humidity (>100%)

### ISSUE THREAD

**Issue by ProfessorFartsalot** [Mrbt0907/Weather2-Remastered#96]
In a jungle biome on a creative world I made, I was able to run `/storm test weather` to discover a humidity value of 109.7% in the 2.8.0 INDEV release.

![image](https://user-images.githubusercontent.com/16886014/188261195-d7a2c05e-143b-411d-ab4d-a762bdc13fda.png)

**Comment by ProfessorFartsalot** [comment]
Likewise, it is possible for Severe Storm probability to exceed 100%: 
![image](https://user-images.githubusercontent.com/16886014/188261371-8d2e8fa6-71da-44f2-ae29-ad1d7551552e.png)

**Comment by Mrbt0907** [comment]
Fixed in the next update.
