### ISSUE TITLE
rain things

### ISSUE THREAD

**Issue by oriolprogamer712** [Mrbt0907/Weather2-Remastered#97]
the rain can be improved a little more
when something is up, for example thunderstorm or just rain, the rain always falls before the storm cloud is up
I show you some photos so you can see

**Comment by oriolprogamer712** [comment]
![Captura de pantalla (202).png](https://user-images.githubusercontent.com/92949450/188800582-79658b5a-7fb4-45d0-bdce-059205ddba08.png)

**Comment by Mrbt0907** [comment]
The range of the rain particles will sometimes exceed the storm cloud. I have made an attempt to tighten up the rain range to be more closer to the cloud particles, but I cannot achieve 100% accuracy without lag.
